# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 845)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/ico/title.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QWidget{background-color: rgb(255, 255, 255);}\n"
"QPushButton{background-color: #b3dbff;border-style:none;border-radius: 10px;}\n"
"\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QPushButton:pressed {  \n"
"    /* 改变背景色 */  \n"
"    background-color:rgb(180, 180, 180);  \n"
"\n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
"\n"
"    /* 使文字有一点移动 */  \n"
"    padding-left:2px;  \n"
"    padding-top:2px;  \n"
"}\n"
"QLineEdit{border: 1px solid #50b8ef;border-radius:5px;}\n"
"QLineEdit:focus{border: 1px solid rgb(50, 179, 255);}\n"
"\n"
"QRadioButton{background-color: #b3dbff;border-radius: 5px;}\n"
"QRadioButton::indicator{width: 17px;height: 17px;}\n"
"QRadioButton::indicator:unchecked{image: url(:/newPrefix/ico/单选.png);}\n"
"QRadioButton::indicator:checked{image: url(:/newPrefix/ico/单选1.png);}\n"
"QRadioButton:hover{\n"
"color:white;\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"QCheckBox::indicator{width: 17px;height: 17px;}\n"
"QCheckBox::indicator:unchecked{image: url(:/newPrefix/ico/多选.png);}\n"
"QCheckBox::indicator:checked{image: url(:/newPrefix/ico/多选1.png);}\n"
"QCheckBox:hover{\n"
"color:white;\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"QTextBrowser{border: 1px solid #50b8ef;border-radius:5px;}\n"
"QTextBrowser:focus{border: 1px solid rgb(50, 179, 255);}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_inExcel = QtWidgets.QPushButton(self.widget)
        self.pushButton_inExcel.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_inExcel.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_inExcel.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/ico/打开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_inExcel.setIcon(icon1)
        self.pushButton_inExcel.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_inExcel.setObjectName("pushButton_inExcel")
        self.horizontalLayout_2.addWidget(self.pushButton_inExcel)
        self.lineEdit_inExcel = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_inExcel.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_inExcel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_inExcel.setReadOnly(True)
        self.lineEdit_inExcel.setObjectName("lineEdit_inExcel")
        self.horizontalLayout_2.addWidget(self.lineEdit_inExcel)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMinimumSize(QtCore.QSize(330, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(330, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(10, 55, 10, 50)
        self.verticalLayout_2.setSpacing(50)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setMinimumSize(QtCore.QSize(300, 200))
        self.widget_4.setMaximumSize(QtCore.QSize(300, 200))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.radioButton_0 = QtWidgets.QRadioButton(self.widget_4)
        self.radioButton_0.setMinimumSize(QtCore.QSize(260, 25))
        self.radioButton_0.setMaximumSize(QtCore.QSize(260, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_0.setFont(font)
        self.radioButton_0.setChecked(True)
        self.radioButton_0.setObjectName("radioButton_0")
        self.verticalLayout_19.addWidget(self.radioButton_0)
        self.radioButton_1 = QtWidgets.QRadioButton(self.widget_4)
        self.radioButton_1.setMinimumSize(QtCore.QSize(260, 25))
        self.radioButton_1.setMaximumSize(QtCore.QSize(260, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setObjectName("radioButton_1")
        self.verticalLayout_19.addWidget(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_4)
        self.radioButton_2.setMinimumSize(QtCore.QSize(260, 25))
        self.radioButton_2.setMaximumSize(QtCore.QSize(260, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_19.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget_4)
        self.radioButton_3.setMinimumSize(QtCore.QSize(260, 25))
        self.radioButton_3.setMaximumSize(QtCore.QSize(260, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_19.addWidget(self.radioButton_3)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget_2.setMinimumSize(QtCore.QSize(300, 200))
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stackedWidget_2.setFont(font)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.stackedWidget_2.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.checkBox_21 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_21.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBox_21.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_21.setFont(font)
        self.checkBox_21.setChecked(True)
        self.checkBox_21.setObjectName("checkBox_21")
        self.verticalLayout_21.addWidget(self.checkBox_21)
        self.checkBox_22 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_22.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBox_22.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_22.setFont(font)
        self.checkBox_22.setChecked(True)
        self.checkBox_22.setObjectName("checkBox_22")
        self.verticalLayout_21.addWidget(self.checkBox_22)
        self.checkBox_23 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_23.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBox_23.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_23.setFont(font)
        self.checkBox_23.setChecked(True)
        self.checkBox_23.setObjectName("checkBox_23")
        self.verticalLayout_21.addWidget(self.checkBox_23)
        self.checkBox_24 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_24.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBox_24.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_24.setFont(font)
        self.checkBox_24.setChecked(True)
        self.checkBox_24.setObjectName("checkBox_24")
        self.verticalLayout_21.addWidget(self.checkBox_24)
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.checkBox_31 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_31.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBox_31.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_31.setFont(font)
        self.checkBox_31.setChecked(True)
        self.checkBox_31.setObjectName("checkBox_31")
        self.verticalLayout_22.addWidget(self.checkBox_31)
        self.checkBox_32 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_32.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBox_32.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_32.setFont(font)
        self.checkBox_32.setChecked(True)
        self.checkBox_32.setObjectName("checkBox_32")
        self.verticalLayout_22.addWidget(self.checkBox_32)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.checkBox_41 = QtWidgets.QCheckBox(self.page_4)
        self.checkBox_41.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBox_41.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_41.setFont(font)
        self.checkBox_41.setChecked(True)
        self.checkBox_41.setObjectName("checkBox_41")
        self.verticalLayout_23.addWidget(self.checkBox_41)
        self.checkBox_42 = QtWidgets.QCheckBox(self.page_4)
        self.checkBox_42.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBox_42.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_42.setFont(font)
        self.checkBox_42.setChecked(True)
        self.checkBox_42.setObjectName("checkBox_42")
        self.verticalLayout_23.addWidget(self.checkBox_42)
        self.stackedWidget_2.addWidget(self.page_4)
        self.verticalLayout_2.addWidget(self.stackedWidget_2)
        self.pushButton_run = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_run.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_run.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_run.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/ico/启动.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_run.setIcon(icon2)
        self.pushButton_run.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_run.setObjectName("pushButton_run")
        self.verticalLayout_2.addWidget(self.pushButton_run, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_page = QtWidgets.QLabel(self.widget_6)
        self.label_page.setText("")
        self.label_page.setObjectName("label_page")
        self.horizontalLayout_4.addWidget(self.label_page)
        self.pushButton_up = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_up.setMinimumSize(QtCore.QSize(20, 25))
        self.pushButton_up.setMaximumSize(QtCore.QSize(20, 25))
        self.pushButton_up.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/ico/上一页.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_up.setIcon(icon3)
        self.pushButton_up.setObjectName("pushButton_up")
        self.horizontalLayout_4.addWidget(self.pushButton_up)
        self.pushButton_down = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_down.setMinimumSize(QtCore.QSize(20, 25))
        self.pushButton_down.setMaximumSize(QtCore.QSize(20, 25))
        self.pushButton_down.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/ico/下一页.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_down.setIcon(icon4)
        self.pushButton_down.setObjectName("pushButton_down")
        self.horizontalLayout_4.addWidget(self.pushButton_down)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_5)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 350))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_5)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 50))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.widget_37 = QtWidgets.QWidget(self.widget_5)
        self.widget_37.setObjectName("widget_37")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_37)
        self.horizontalLayout_20.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout_20.setSpacing(15)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem1)
        self.pushButton_outImage = QtWidgets.QPushButton(self.widget_37)
        self.pushButton_outImage.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_outImage.setMaximumSize(QtCore.QSize(100, 25))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/ico/图片.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_outImage.setIcon(icon5)
        self.pushButton_outImage.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_outImage.setObjectName("pushButton_outImage")
        self.horizontalLayout_20.addWidget(self.pushButton_outImage)
        self.pushButton_outExcel = QtWidgets.QPushButton(self.widget_37)
        self.pushButton_outExcel.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_outExcel.setMaximumSize(QtCore.QSize(100, 25))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/ico/数据.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_outExcel.setIcon(icon6)
        self.pushButton_outExcel.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_outExcel.setObjectName("pushButton_outExcel")
        self.horizontalLayout_20.addWidget(self.pushButton_outExcel)
        self.verticalLayout_3.addWidget(self.widget_37)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "锂离子电池系统故障诊断软件"))
        self.pushButton_inExcel.setText(_translate("Form", "选择文件"))
        self.radioButton_0.setText(_translate("Form", "整车故障分析"))
        self.radioButton_1.setText(_translate("Form", "单体电压分析"))
        self.radioButton_2.setText(_translate("Form", "温度分析"))
        self.radioButton_3.setText(_translate("Form", "充电电压曲线一致性分析"))
        self.checkBox_21.setText(_translate("Form", "电压差及变化率"))
        self.checkBox_22.setText(_translate("Form", "最大值、最小值和极差"))
        self.checkBox_23.setText(_translate("Form", "电压偏离度"))
        self.checkBox_24.setText(_translate("Form", "充电起始电压和充电结束电压及排名"))
        self.checkBox_31.setText(_translate("Form", "温度差及变化率"))
        self.checkBox_32.setText(_translate("Form", "最大值、最小值和极差"))
        self.checkBox_41.setText(_translate("Form", "充电曲线距离分析"))
        self.checkBox_42.setText(_translate("Form", "局部离群点检测"))
        self.pushButton_run.setText(_translate("Form", "运行"))
        self.pushButton_outImage.setText(_translate("Form", "导出图片"))
        self.pushButton_outExcel.setText(_translate("Form", "导出表格"))
import image_rc
